/**
 * Integration tests for the `ssh-exec` backend client.
 *
 * We can't reach a real remote host in CI, so we simulate the SSH tool: a fake
 * `ssh` on PATH captures its argv and then runs the remote command string
 * locally (a stand-in for a remote that shares the filesystem). Combined with a
 * real key generated by `ssh-keygen`, this exercises the client end-to-end —
 * command routing, argument escaping, exit-code passthrough, the `-i` key
 * option, port/user/cwd handling, and the hardened ssh options.
 *
 * Unix-only (the client is a bash script); skipped on Windows.
 */

import { describe, test, expect, beforeAll, afterAll } from "bun:test";
import { spawnSync } from "node:child_process";
import {
  mkdtempSync,
  realpathSync,
  mkdirSync,
  writeFileSync,
  chmodSync,
  rmSync,
  existsSync,
  readFileSync,
  unlinkSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SSH_EXEC_SCRIPT } from "../src/templates";

const runSuite = process.platform === "win32" ? describe.skip : describe;

runSuite("ssh-exec (simulated SSH tool)", () => {
  let root: string;
  let binDir: string;
  let sshExecPath: string;
  let capturePath: string;
  let keyPath: string;

  beforeAll(() => {
    // realpath: on macOS tmpdir() is under the /var -> /private/var symlink, and
    // the client's `pwd` reports the resolved path.
    root = realpathSync(mkdtempSync(join(tmpdir(), "heretic-ssh-")));
    binDir = join(root, "bin");
    mkdirSync(binDir);
    capturePath = join(root, "capture.txt");

    // The client under test.
    sshExecPath = join(root, "ssh-exec");
    writeFileSync(sshExecPath, SSH_EXEC_SCRIPT);
    chmodSync(sshExecPath, 0o755);

    // Fake `ssh`: record argv, then execute the remote command string locally so
    // real stdout/stderr and the exit code flow back through `exec ssh`.
    const fakeSsh = [
      "#!/usr/bin/env bash",
      'printf "%s\\n" "$@" > "$SSH_CAPTURE"',
      'remote="${!#}"', // last positional argument is the remote command
      'exec bash -c "$remote"',
      "",
    ].join("\n");
    writeFileSync(join(binDir, "ssh"), fakeSsh);
    chmodSync(join(binDir, "ssh"), 0o755);

    // Helper so exit-code tests don't depend on shell `sh -c` quoting.
    writeFileSync(join(binDir, "exit-with"), '#!/usr/bin/env bash\nexit "${1:-0}"\n');
    chmodSync(join(binDir, "exit-with"), 0o755);

    // A real keypair for the -i assertions.
    keyPath = join(root, "id_test");
    const kg = spawnSync("ssh-keygen", ["-t", "ed25519", "-N", "", "-f", keyPath, "-q"], {
      encoding: "utf8",
    });
    if (kg.status !== 0) {
      throw new Error(`ssh-keygen failed: ${kg.stderr || kg.stdout}`);
    }
  });

  afterAll(() => {
    if (root && existsSync(root)) rmSync(root, { recursive: true, force: true });
  });

  interface RunResult {
    stdout: string;
    stderr: string;
    code: number | null;
    argv: string[];
  }

  function runSshExec(
    args: string[],
    opts: { env?: Record<string, string>; cwd?: string } = {}
  ): RunResult {
    if (existsSync(capturePath)) unlinkSync(capturePath); // avoid stale reads
    const env: Record<string, string> = {
      ...process.env,
      PATH: `${binDir}:${process.env.PATH}`,
      SSH_CAPTURE: capturePath,
      ...(opts.env || {}),
    };
    const res = spawnSync("bash", [sshExecPath, ...args], {
      env,
      cwd: opts.cwd || root,
      encoding: "utf8",
    });
    const argv = existsSync(capturePath)
      ? readFileSync(capturePath, "utf8").split("\n").filter(Boolean)
      : [];
    return { stdout: res.stdout || "", stderr: res.stderr || "", code: res.status, argv };
  }

  test("ssh-keygen produced a real keypair", () => {
    expect(existsSync(keyPath)).toBe(true);
    expect(existsSync(`${keyPath}.pub`)).toBe(true);
  });

  test("routes to user@host with the remote cd + command", () => {
    const r = runSshExec(["echo", "hi"], {
      env: {
        SSH_HOST: "remote.example",
        SSH_USER: "builder",
        SSH_PORT: "2222",
        SSH_HOST_CWD: "/srv/ws",
      },
    });
    expect(r.argv).toContain("builder@remote.example");
    // The final argument is the remote command: cd <cwd> && <cmd>.
    expect(r.argv[r.argv.length - 1]).toBe("cd /srv/ws && echo hi");
  });

  test("passes the port with -p", () => {
    const r = runSshExec(["true"], { env: { SSH_HOST: "h", SSH_PORT: "2222" } });
    const i = r.argv.indexOf("-p");
    expect(i).toBeGreaterThanOrEqual(0);
    expect(r.argv[i + 1]).toBe("2222");
  });

  test("defaults user to 'agent' and port to 22", () => {
    const r = runSshExec(["true"], { env: { SSH_HOST: "h" } });
    expect(r.argv).toContain("agent@h");
    const i = r.argv.indexOf("-p");
    expect(r.argv[i + 1]).toBe("22");
  });

  test("uses hardened ssh options", () => {
    const r = runSshExec(["true"], { env: { SSH_HOST: "h" } });
    expect(r.argv).toContain("StrictHostKeyChecking=no");
    expect(r.argv).toContain("UserKnownHostsFile=/dev/null");
    expect(r.argv).toContain("LogLevel=ERROR");
  });

  test("propagates the remote exit code", () => {
    const r = runSshExec(["exit-with", "7"], { env: { SSH_HOST: "h" } });
    expect(r.code).toBe(7);
  });

  test("keeps a multi-word argument as one argument on the remote", () => {
    // cwd = root (exists) so the remote `cd` succeeds and echo actually runs.
    const r = runSshExec(["echo", "a b"], { env: { SSH_HOST: "h" }, cwd: root });
    expect(r.stdout.trim()).toBe("a b");
  });

  test("adds -i when the key file exists", () => {
    const r = runSshExec(["true"], { env: { SSH_HOST: "h", SSH_KEY_PATH: keyPath } });
    const i = r.argv.indexOf("-i");
    expect(i).toBeGreaterThanOrEqual(0);
    expect(r.argv[i + 1]).toBe(keyPath);
  });

  test("omits -i when the key file does not exist", () => {
    const r = runSshExec(["true"], {
      env: { SSH_HOST: "h", SSH_KEY_PATH: join(root, "does-not-exist") },
    });
    expect(r.argv).not.toContain("-i");
  });

  test("defaults the remote cwd to the current directory", () => {
    const r = runSshExec(["true"], { env: { SSH_HOST: "h" }, cwd: root });
    expect(r.argv[r.argv.length - 1]).toBe(`cd ${root} && true`);
  });

  test("fails clearly when SSH_HOST is unset", () => {
    const env: Record<string, string> = {
      ...process.env,
      PATH: `${binDir}:${process.env.PATH}`,
      SSH_CAPTURE: capturePath,
    };
    delete env.SSH_HOST;
    const res = spawnSync("bash", [sshExecPath, "true"], { env, cwd: root, encoding: "utf8" });
    expect(res.status).not.toBe(0);
    expect(res.stderr).toContain("SSH_HOST");
  });
});
